---
title: Fundación Mamá Sena
timezone: UTC
collections:
  posts:
    title: Noticias
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image:
    layout: post
    author: Admin
    has_comments: true
    short_description:
acronym: FUNDASENA
email: fundacionmamasena@gmail.com
description: Fundación Mamá Sena es una institución sin fines de lucro que se propone
  la recomposición de la sociedad a través de procesos de reflexión, capacitación
  y acción comunitaria para el crecimiento en valores humanos.
twitter_username: fundasenard
baseurl: ''
url: https://fundasena.org
markdown: kramdown
tag_manager_id: GTM-W9SZGPG
